//
// GoldenVectorTests.swift
//  ThinkingOrb
//
// Created by persuara on 9/21/26
//
//  Compares the Swift engine against the TypeScript engine's own output.
//
//  `orbs-golden.json` was generated by the original `thinking-orbs` library:
//  for 9 states × 2 sizes × 4 timestamps it records every dot
//  (x, y, z, radius, ink, alpha) and every line, already z-sorted, plus the
//  fully-resolved options of each preset. If the port drifts by even a
//  fraction of a pixel, these tests fail.
//

import Foundation
import Testing

@testable import ThinkingOrbKit

/// The decoded golden file.
struct Golden: Decodable, Sendable {
    struct Preset: Decodable, Sendable {
        let mode: String
        let speed: Double
        let opts: [String: Double]
    }

    struct Case: Decodable, Sendable, CustomTestStringConvertible {
        let key: String
        let state: String
        let size: Int
        let mode: String
        let t: Double
        let dotCount: Int
        let lineCount: Int
        /// Stride 6: x, y, z, r, white, a.
        let dots: [Double]
        /// Stride 7: x1, y1, x2, y2, white, a, w.
        let lines: [Double]

        var testDescription: String { key }
    }

    /// Reference values are stored to 6 decimals, so this is the agreement we can demand.
    let tolerance: Double
    let resolved: [String: Preset]
    let cases: [Case]

    static let shared: Golden = {
        guard
            let url = Bundle.module.url(forResource: "orbs-golden", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let golden = try? JSONDecoder().decode(Golden.self, from: data)
        else { fatalError("orbs-golden.json is missing from the test bundle or malformed") }
        return golden
    }()
}

@Suite("Golden vectors (TypeScript reference)")
struct GoldenVectorTests {
    @Test("resolved options match the reference", arguments: Golden.shared.resolved.keys.sorted())
    func resolvedPreset(key: String) throws {
        let parts = key.split(separator: "-")
        let state = try #require(OrbState(rawValue: String(parts[0])))
        let size = try #require(Int(parts[1]).map { OrbSize(CGFloat($0)) })
        let reference = try #require(Golden.shared.resolved[key])

        let mine = Resolved(state: state, size: size)
        #expect(mine.mode.rawValue == reference.mode)
        #expect(abs(mine.speed - reference.speed) < 1e-9)

        let options = Dictionary(uniqueKeysWithValues: mine.opts.values.map { ($0.key.rawValue, $0.value) })
        #expect(Set(options.keys) == Set(reference.opts.keys))
        for (name, value) in reference.opts {
            #expect(abs((options[name] ?? .nan) - value) < 1e-9, "option \(name)")
        }
    }

    @Test("every option key in the spec is an OptKey case, and vice versa")
    func optionKeysMatchSpec() {
        let specKeys = Set(Golden.shared.resolved.values.flatMap { $0.opts.keys })
        #expect(specKeys == Set(OptKey.allCases.map(\.rawValue)))
    }

    @Test("frame geometry matches the reference", arguments: Golden.shared.cases)
    func frameMatchesReference(_ reference: Golden.Case) throws {
        let state = try #require(OrbState(rawValue: reference.state))
        let size = OrbSize(CGFloat(reference.size))
        let resolved = Resolved(state: state, size: size)
        let frame = resolved.mode.frame(size: Double(size.points), time: reference.t, options: resolved.opts)

        #expect(frame.dots.count == reference.dotCount)
        #expect(frame.lines.count == reference.lineCount)
        try #require(frame.dots.count * 6 == reference.dots.count)
        try #require(frame.lines.count * 7 == reference.lines.count)

        func error(_ dot: Dot, _ index: Int) -> Double {
            let ref = reference.dots[(index * 6)..<(index * 6 + 6)]
            let mine = [dot.x, dot.y, dot.z, dot.r, dot.white, dot.a]
            return zip(mine, ref).map { abs($0 - $1) }.max() ?? 0
        }

        // Draw order among dots at (nearly) the same depth is decided by floating-point
        // noise — the face-on ring has dozens at z ≈ 0, and the reference z is rounded to
        // 6 decimals — so it is not something to assert. Within a run of tied depths we
        // require the same SET of dots; everywhere else, the exact position.
        var worst = 0.0
        var start = 0
        while start < frame.dots.count {
            var end = start + 1
            while end < frame.dots.count,
                abs(reference.dots[end * 6 + 2] - reference.dots[(end - 1) * 6 + 2]) <= 2e-6
            {
                end += 1
            }
            var pool = Array(start..<end)
            for index in start..<end {
                let errors = pool.map { error(frame.dots[$0], index) }
                guard let best = errors.enumerated().min(by: { $0.element < $1.element }) else { break }
                worst = max(worst, best.element)
                pool.remove(at: best.offset)
            }
            start = end
        }

        // Lines are not sorted among themselves; they come out in generation order.
        for (i, line) in frame.lines.enumerated() {
            let ref = reference.lines[(i * 7)..<(i * 7 + 7)]
            let mine = [line.x1, line.y1, line.x2, line.y2, line.white, line.a, line.w]
            worst = max(worst, zip(mine, ref).map { abs($0 - $1) }.max() ?? 0)
        }

        #expect(worst <= Golden.shared.tolerance, "worst absolute error \(worst)")
    }
}
